/*
Exercise 1: (1) Create a List (try both ArrayList and LinkedList) and fill it using
Countries. Sort the list and print it, then apply Collections.shuffle( ) to the list
repeatedly, printing it each time so that you can see how the shuffle( ) method randomizes
the list differently each time.
 */
package Chapter17;
import java.util.*;
import Countries.Countries;

public class Ex1 {
    public static void main(String[] args) {
        List<String> arrayList = new ArrayList<>();
        for(int i = 0; i < Countries.DATA.length; i++) {
            arrayList.add(Countries.DATA[i][0]);
        }
        List<String> linkedList = new LinkedList<>();
        for(int i = 0; i < Countries.DATA.length; i++) {
            linkedList.add(Countries.DATA[i][1]);
        }
        System.out.println(arrayList);
        System.out.println(linkedList);
        Collections.sort(arrayList);
        Collections.sort(linkedList);
        System.out.println("Sorted countries: " + arrayList);
        System.out.println("Sorted capitals: " + linkedList);
        for(int i = 0; i < 3; i++) {
            Collections.shuffle(arrayList);
            Collections.shuffle(linkedList);
            System.out.println("Shuffled countries: " + arrayList);
            System.out.println("Shuffled capitals: " + linkedList);
        }

    }
}
/* Output:
[ALGERIA, ANGOLA, BENIN, BOTSWANA, BURKINA FASO, BURUNDI, CAMEROON, CAPE VERDE, CENTRAL AFRICAN REPUBLIC, CHAD, COMOROS, CONGO, DJIBOUTI, EGYPT, EQUATORIAL GUINEA, ERITREA, ETHIOPIA, GABON, THE GAMBIA, GHANA, GUINEA, BISSAU, COTE D’IVOIR (IVORY COAST), KENYA, LESOTHO, LIBERIA, LIBYA, MADAGASCAR, MALAWI, MALI, MAURITANIA, MAURITIUS, MOROCCO, MOZAMBIQUE, NAMIBIA, NIGER, NIGERIA, RWANDA, SAO TOME E PRINCIPE, SENEGAL, SEYCHELLES, SIERRA LEONE, SOMALIA, SOUTH AFRICA, SUDAN, SWAZILAND, TANZANIA, TOGO, TUNISIA, UGANDA, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), ZAMBIA, ZIMBABWE, AFGHANISTAN, BAHRAIN, BANGLADESH, BHUTAN, BRUNEI, CAMBODIA, CHINA, CYPRUS, INDIA, INDONESIA, IRAN, IRAQ, ISRAEL, JAPAN, JORDAN, KUWAIT, LAOS, LEBANON, MALAYSIA, THE MALDIVES, MONGOLIA, MYANMAR (BURMA), NEPAL, NORTH KOREA, OMAN, PAKISTAN, PHILIPPINES, QATAR, SAUDI ARABIA, SINGAPORE, SOUTH KOREA, SRI LANKA, SYRIA, TAIWAN (REPUBLIC OF CHINA), THAILAND, TURKEY, UNITED ARAB EMIRATES, VIETNAM, YEMEN, AUSTRALIA, FIJI, KIRIBATI, MARSHALL ISLANDS, MICRONESIA, NAURU, NEW ZEALAND, PALAU, PAPUA NEW GUINEA, SOLOMON ISLANDS, TONGA, TUVALU, VANUATU, WESTERN SAMOA, ARMENIA, AZERBAIJAN, BELARUS (BYELORUSSIA), BULGARIA, GEORGIA, KAZAKSTAN, KYRGYZSTAN, MOLDOVA, RUSSIA, TAJIKISTAN, TURKMENISTAN, UKRAINE, UZBEKISTAN, ALBANIA, ANDORRA, AUSTRIA, BELGIUM, BOSNIA, HERZEGOVINA, CROATIA, CZECH REPUBLIC, DENMARK, ESTONIA, FINLAND, FRANCE, GERMANY, GREECE, HUNGARY, ICELAND, IRELAND, ITALY, LATVIA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MACEDONIA, MALTA, MONACO, MONTENEGRO, THE NETHERLANDS, NORWAY, POLAND, PORTUGAL, ROMANIA, SAN MARINO, SERBIA, SLOVAKIA, SLOVENIA, SPAIN, SWEDEN, SWITZERLAND, UNITED KINGDOM, VATICAN CITY, ANTIGUA AND BARBUDA, BAHAMAS, BARBADOS, BELIZE, CANADA, COSTA RICA, CUBA, DOMINICA, DOMINICAN REPUBLIC, EL SALVADOR, GRENADA, GUATEMALA, HAITI, HONDURAS, JAMAICA, MEXICO, NICARAGUA, PANAMA, ST. KITTS, NEVIS, ST. LUCIA, ST. VINCENT AND THE GRENADINES, UNITED STATES OF AMERICA, ARGENTINA, BOLIVIA, BRAZIL, CHILE, COLOMBIA, ECUADOR, GUYANA, PARAGUAY, PERU, SURINAME, TRINIDAD AND TOBAGO, URUGUAY, VENEZUELA]
[Algiers, Luanda, Porto-Novo, Gaberone, Ouagadougou, Bujumbura, Yaounde, Praia, Bangui, N’djamena, Moroni, Brazzaville, Dijibouti, Cairo, Malabo, Asmara, Addis Ababa, Libreville, Banjul, Accra, Conakry, Bissau, Yamoussoukro, Nairobi, Maseru, Monrovia, Tripoli, Antananarivo, Lilongwe, Bamako, Nouakchott, Port Louis, Rabat, Maputo, Windhoek, Niamey, Abuja, Kigali, Sao Tome, Dakar, Victoria, Freetown, Mogadishu, Pretoria/Cape Town, Khartoum, Mbabane, Dodoma, Lome, Tunis, Kampala, Kinshasa, Lusaka, Harare, Kabul, Manama, Dhaka, Thimphu, Bandar Seri Begawan, Phnom Penh, Beijing, Nicosia, New Delhi, Jakarta, Tehran, Baghdad, Jerusalem, Tokyo, Amman, Kuwait City, Vientiane, Beirut, Kuala Lumpur, Male, Ulan Bator, Rangoon, Katmandu, P’yongyang, Muscat, Islamabad, Manila, Doha, Riyadh, Singapore, Seoul, Colombo, Damascus, Taipei, Bangkok, Ankara, Abu Dhabi, Hanoi, Sana’a, Canberra, Suva, Bairiki, Dalap-Uliga-Darrit, Palikir, Yaren, Wellington, Koror, Port Moresby, Honaira, Nuku’alofa, Fongafale, < Port-Vila, Apia, Yerevan, Baku, Minsk, Sofia, Tbilisi, Almaty, Alma-Ata, Chisinau, Moscow, Dushanbe, Ashkabad, Kyiv, Tashkent, Tirana, Andorra la Vella, Vienna, Brussels, -, Sarajevo, Zagreb, Prague, Copenhagen, Tallinn, Helsinki, Paris, Berlin, Athens, Budapest, Reykjavik, Dublin, Rome, Riga, Vaduz, Vilnius, Luxembourg, Skopje, Valletta, Monaco, Podgorica, Amsterdam, Oslo, Warsaw, Lisbon, Bucharest, San Marino, Belgrade, Bratislava, Ljuijana, Madrid, Stockholm, Berne, London, ---, Saint John’s, Nassau, Bridgetown, Belmopan, Ottawa, San Jose, Havana, Roseau, Santo Domingo, San Salvador, Saint George’s, Guatemala City, Port-au-Prince, Tegucigalpa, Kingston, Mexico City, Managua, Panama City, -, Basseterre, Castries, Kingstown, Washington, D.C., Buenos Aires, Sucre (legal)/La Paz(administrative), Brasilia, Santiago, Bogota, Quito, Georgetown, Asuncion, Lima, Paramaribo, Port of Spain, Montevideo, Caracas]
Sorted countries: [AFGHANISTAN, ALBANIA, ALGERIA, ANDORRA, ANGOLA, ANTIGUA AND BARBUDA, ARGENTINA, ARMENIA, AUSTRALIA, AUSTRIA, AZERBAIJAN, BAHAMAS, BAHRAIN, BANGLADESH, BARBADOS, BELARUS (BYELORUSSIA), BELGIUM, BELIZE, BENIN, BHUTAN, BISSAU, BOLIVIA, BOSNIA, BOTSWANA, BRAZIL, BRUNEI, BULGARIA, BURKINA FASO, BURUNDI, CAMBODIA, CAMEROON, CANADA, CAPE VERDE, CENTRAL AFRICAN REPUBLIC, CHAD, CHILE, CHINA, COLOMBIA, COMOROS, CONGO, COSTA RICA, COTE D’IVOIR (IVORY COAST), CROATIA, CUBA, CYPRUS, CZECH REPUBLIC, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), DENMARK, DJIBOUTI, DOMINICA, DOMINICAN REPUBLIC, ECUADOR, EGYPT, EL SALVADOR, EQUATORIAL GUINEA, ERITREA, ESTONIA, ETHIOPIA, FIJI, FINLAND, FRANCE, GABON, GEORGIA, GERMANY, GHANA, GREECE, GRENADA, GUATEMALA, GUINEA, GUYANA, HAITI, HERZEGOVINA, HONDURAS, HUNGARY, ICELAND, INDIA, INDONESIA, IRAN, IRAQ, IRELAND, ISRAEL, ITALY, JAMAICA, JAPAN, JORDAN, KAZAKSTAN, KENYA, KIRIBATI, KUWAIT, KYRGYZSTAN, LAOS, LATVIA, LEBANON, LESOTHO, LIBERIA, LIBYA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MACEDONIA, MADAGASCAR, MALAWI, MALAYSIA, MALI, MALTA, MARSHALL ISLANDS, MAURITANIA, MAURITIUS, MEXICO, MICRONESIA, MOLDOVA, MONACO, MONGOLIA, MONTENEGRO, MOROCCO, MOZAMBIQUE, MYANMAR (BURMA), NAMIBIA, NAURU, NEPAL, NEVIS, NEW ZEALAND, NICARAGUA, NIGER, NIGERIA, NORTH KOREA, NORWAY, OMAN, PAKISTAN, PALAU, PANAMA, PAPUA NEW GUINEA, PARAGUAY, PERU, PHILIPPINES, POLAND, PORTUGAL, QATAR, ROMANIA, RUSSIA, RWANDA, SAN MARINO, SAO TOME E PRINCIPE, SAUDI ARABIA, SENEGAL, SERBIA, SEYCHELLES, SIERRA LEONE, SINGAPORE, SLOVAKIA, SLOVENIA, SOLOMON ISLANDS, SOMALIA, SOUTH AFRICA, SOUTH KOREA, SPAIN, SRI LANKA, ST. KITTS, ST. LUCIA, ST. VINCENT AND THE GRENADINES, SUDAN, SURINAME, SWAZILAND, SWEDEN, SWITZERLAND, SYRIA, TAIWAN (REPUBLIC OF CHINA), TAJIKISTAN, TANZANIA, THAILAND, THE GAMBIA, THE MALDIVES, THE NETHERLANDS, TOGO, TONGA, TRINIDAD AND TOBAGO, TUNISIA, TURKEY, TURKMENISTAN, TUVALU, UGANDA, UKRAINE, UNITED ARAB EMIRATES, UNITED KINGDOM, UNITED STATES OF AMERICA, URUGUAY, UZBEKISTAN, VANUATU, VATICAN CITY, VENEZUELA, VIETNAM, WESTERN SAMOA, YEMEN, ZAMBIA, ZIMBABWE]
Sorted capitals: [-, -, ---, < Port-Vila, Abu Dhabi, Abuja, Accra, Addis Ababa, Algiers, Alma-Ata, Almaty, Amman, Amsterdam, Andorra la Vella, Ankara, Antananarivo, Apia, Ashkabad, Asmara, Asuncion, Athens, Baghdad, Bairiki, Baku, Bamako, Bandar Seri Begawan, Bangkok, Bangui, Banjul, Basseterre, Beijing, Beirut, Belgrade, Belmopan, Berlin, Berne, Bissau, Bogota, Brasilia, Bratislava, Brazzaville, Bridgetown, Brussels, Bucharest, Budapest, Buenos Aires, Bujumbura, Cairo, Canberra, Caracas, Castries, Chisinau, Colombo, Conakry, Copenhagen, Dakar, Dalap-Uliga-Darrit, Damascus, Dhaka, Dijibouti, Dodoma, Doha, Dublin, Dushanbe, Fongafale, Freetown, Gaberone, Georgetown, Guatemala City, Hanoi, Harare, Havana, Helsinki, Honaira, Islamabad, Jakarta, Jerusalem, Kabul, Kampala, Katmandu, Khartoum, Kigali, Kingston, Kingstown, Kinshasa, Koror, Kuala Lumpur, Kuwait City, Kyiv, Libreville, Lilongwe, Lima, Lisbon, Ljuijana, Lome, London, Luanda, Lusaka, Luxembourg, Madrid, Malabo, Male, Managua, Manama, Manila, Maputo, Maseru, Mbabane, Mexico City, Minsk, Mogadishu, Monaco, Monrovia, Montevideo, Moroni, Moscow, Muscat, Nairobi, Nassau, New Delhi, Niamey, Nicosia, Nouakchott, Nuku’alofa, N’djamena, Oslo, Ottawa, Ouagadougou, Palikir, Panama City, Paramaribo, Paris, Phnom Penh, Podgorica, Port Louis, Port Moresby, Port of Spain, Port-au-Prince, Porto-Novo, Prague, Praia, Pretoria/Cape Town, P’yongyang, Quito, Rabat, Rangoon, Reykjavik, Riga, Riyadh, Rome, Roseau, Saint George’s, Saint John’s, San Jose, San Marino, San Salvador, Sana’a, Santiago, Santo Domingo, Sao Tome, Sarajevo, Seoul, Singapore, Skopje, Sofia, Stockholm, Sucre (legal)/La Paz(administrative), Suva, Taipei, Tallinn, Tashkent, Tbilisi, Tegucigalpa, Tehran, Thimphu, Tirana, Tokyo, Tripoli, Tunis, Ulan Bator, Vaduz, Valletta, Victoria, Vienna, Vientiane, Vilnius, Warsaw, Washington, D.C., Wellington, Windhoek, Yamoussoukro, Yaounde, Yaren, Yerevan, Zagreb]
Shuffled countries: [ST. VINCENT AND THE GRENADINES, SLOVENIA, BOSNIA, PHILIPPINES, FINLAND, ITALY, SOMALIA, ANTIGUA AND BARBUDA, NEW ZEALAND, BURKINA FASO, SYRIA, ST. LUCIA, SAO TOME E PRINCIPE, MACEDONIA, ESTONIA, MALAWI, BURUNDI, POLAND, COSTA RICA, CHINA, VENEZUELA, WESTERN SAMOA, LAOS, BAHRAIN, INDIA, YEMEN, ZAMBIA, MICRONESIA, ETHIOPIA, ICELAND, PANAMA, ERITREA, SAUDI ARABIA, CAMEROON, ARGENTINA, TRINIDAD AND TOBAGO, PARAGUAY, JORDAN, SWAZILAND, CAPE VERDE, CYPRUS, SWITZERLAND, SEYCHELLES, LIECHTENSTEIN, MALAYSIA, SIERRA LEONE, EGYPT, LATVIA, EL SALVADOR, BARBADOS, ST. KITTS, CANADA, AFGHANISTAN, NEVIS, ISRAEL, ANGOLA, SPAIN, CROATIA, NORWAY, DOMINICA, GERMANY, THE NETHERLANDS, MOROCCO, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), BISSAU, MONGOLIA, MEXICO, NAURU, PERU, GREECE, VANUATU, IRAN, CHAD, MONACO, PAPUA NEW GUINEA, FRANCE, CUBA, QATAR, ALGERIA, ECUADOR, MONTENEGRO, BHUTAN, MOLDOVA, PAKISTAN, AZERBAIJAN, PALAU, UNITED STATES OF AMERICA, JAMAICA, GUYANA, NEPAL, PORTUGAL, GABON, SURINAME, NICARAGUA, GEORGIA, SOLOMON ISLANDS, AUSTRALIA, TURKEY, BOTSWANA, IRAQ, MALTA, UNITED ARAB EMIRATES, TANZANIA, RWANDA, ROMANIA, TUNISIA, GRENADA, LEBANON, KIRIBATI, MYANMAR (BURMA), ANDORRA, ARMENIA, LITHUANIA, SINGAPORE, KUWAIT, RUSSIA, OMAN, THE MALDIVES, KENYA, GUATEMALA, SOUTH AFRICA, TAJIKISTAN, NIGER, COMOROS, URUGUAY, BANGLADESH, ZIMBABWE, THE GAMBIA, MOZAMBIQUE, BAHAMAS, THAILAND, INDONESIA, SERBIA, AUSTRIA, COTE D’IVOIR (IVORY COAST), TUVALU, SLOVAKIA, BENIN, COLOMBIA, BRUNEI, MARSHALL ISLANDS, SUDAN, BELARUS (BYELORUSSIA), VIETNAM, MAURITANIA, HAITI, GUINEA, NORTH KOREA, UKRAINE, TURKMENISTAN, UZBEKISTAN, MAURITIUS, ALBANIA, BOLIVIA, HERZEGOVINA, LUXEMBOURG, UGANDA, CENTRAL AFRICAN REPUBLIC, NIGERIA, UNITED KINGDOM, DOMINICAN REPUBLIC, LIBERIA, VATICAN CITY, SOUTH KOREA, CONGO, TONGA, HONDURAS, FIJI, HUNGARY, BULGARIA, BRAZIL, GHANA, BELGIUM, SAN MARINO, KYRGYZSTAN, SRI LANKA, DJIBOUTI, JAPAN, BELIZE, MALI, SWEDEN, TAIWAN (REPUBLIC OF CHINA), KAZAKSTAN, CAMBODIA, EQUATORIAL GUINEA, LIBYA, LESOTHO, CHILE, CZECH REPUBLIC, SENEGAL, NAMIBIA, MADAGASCAR, DENMARK, TOGO, IRELAND]
Shuffled capitals: [Dhaka, Victoria, Tegucigalpa, Conakry, Maseru, Georgetown, Bogota, Belmopan, Taipei, Accra, Andorra la Vella, Sao Tome, Berlin, Kingstown, Ljuijana, Riyadh, San Marino, Castries, Bujumbura, Amman, Islamabad, Windhoek, Tehran, Lima, Skopje, Buenos Aires, Minsk, Dalap-Uliga-Darrit, Katmandu, Prague, Lilongwe, Sarajevo, Ottawa, Rangoon, Pretoria/Cape Town, Paramaribo, Damascus, Muscat, New Delhi, Palikir, Bridgetown, Baku, Kingston, Gaberone, Baghdad, Jakarta, Ulan Bator, Alma-Ata, Tirana, Port Louis, Moroni, Kuwait City, Bucharest, Basseterre, Honaira, Bangkok, Thimphu, Saint George’s, Havana, -, Bandar Seri Begawan, Dakar, Kampala, Sana’a, Addis Ababa, Kuala Lumpur, Jerusalem, Tashkent, Brussels, Almaty, Male, Abu Dhabi, Athens, Yaounde, Phnom Penh, Beirut, Antananarivo, Freetown, Brazzaville, Dodoma, Monaco, London, Asmara, Yerevan, Vientiane, Rabat, Tbilisi, Banjul, Riga, Helsinki, Malabo, Bamako, Reykjavik, Beijing, Monrovia, Mexico City, Tripoli, Harare, ---, Suva, Vienna, Saint John’s, Kabul, Luanda, Moscow, Praia, Seoul, Yaren, Doha, P’yongyang, Warsaw, Kinshasa, Lusaka, Colombo, Santiago, Ouagadougou, Valletta, Asuncion, Stockholm, Dublin, Sofia, Madrid, Bangui, Tunis, Sucre (legal)/La Paz(administrative), Vaduz, Port of Spain, Cairo, Tallinn, Kigali, Nairobi, < Port-Vila, Nicosia, Brasilia, Bratislava, Nouakchott, Guatemala City, Zagreb, Ashkabad, Berne, Panama City, Nassau, Maputo, Mbabane, Oslo, Dijibouti, Mogadishu, Podgorica, Lisbon, Manama, Abuja, Luxembourg, Paris, Montevideo, Ankara, Port-au-Prince, Wellington, Khartoum, Santo Domingo, Port Moresby, Libreville, Chisinau, Dushanbe, Singapore, Caracas, Vilnius, Koror, Budapest, Nuku’alofa, San Salvador, Canberra, Copenhagen, Yamoussoukro, Bairiki, Roseau, Washington, D.C., Niamey, Amsterdam, San Jose, Apia, Manila, Fongafale, Tokyo, Hanoi, Porto-Novo, Rome, Belgrade, Quito, Bissau, Lome, Kyiv, -, Managua, N’djamena, Algiers]
Shuffled countries: [LITHUANIA, THE MALDIVES, UNITED ARAB EMIRATES, UZBEKISTAN, TURKEY, CHILE, KAZAKSTAN, BAHRAIN, ICELAND, ZAMBIA, KIRIBATI, COMOROS, TUNISIA, WESTERN SAMOA, MEXICO, BHUTAN, THAILAND, NAMIBIA, MONACO, SAUDI ARABIA, MALI, ARMENIA, PALAU, CUBA, GUYANA, DENMARK, BELIZE, GRENADA, ST. LUCIA, BOTSWANA, RWANDA, SINGAPORE, PHILIPPINES, KYRGYZSTAN, BENIN, LUXEMBOURG, ECUADOR, HUNGARY, MALAYSIA, UKRAINE, SOMALIA, VIETNAM, LESOTHO, CAMEROON, TOGO, DOMINICAN REPUBLIC, SEYCHELLES, ALGERIA, DJIBOUTI, SAO TOME E PRINCIPE, MOZAMBIQUE, SENEGAL, BOLIVIA, LEBANON, ISRAEL, PAPUA NEW GUINEA, AUSTRALIA, ITALY, SRI LANKA, KENYA, CANADA, SOUTH AFRICA, BANGLADESH, BRUNEI, MOROCCO, PAKISTAN, BULGARIA, EQUATORIAL GUINEA, ERITREA, THE NETHERLANDS, MALTA, OMAN, LATVIA, CONGO, NEVIS, BELGIUM, ST. KITTS, ANGOLA, COTE D’IVOIR (IVORY COAST), NICARAGUA, HAITI, MYANMAR (BURMA), VANUATU, SOUTH KOREA, CAMBODIA, MONGOLIA, PERU, TANZANIA, NIGERIA, LIECHTENSTEIN, BISSAU, UNITED STATES OF AMERICA, SPAIN, BRAZIL, MALAWI, BURKINA FASO, BAHAMAS, GHANA, MACEDONIA, IRAN, NORWAY, NEPAL, MOLDOVA, ANDORRA, SWAZILAND, LIBYA, NEW ZEALAND, CROATIA, VENEZUELA, CZECH REPUBLIC, JORDAN, BARBADOS, SWEDEN, GABON, SAN MARINO, MADAGASCAR, LIBERIA, ANTIGUA AND BARBUDA, GEORGIA, CHINA, POLAND, DOMINICA, INDIA, JAPAN, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), CYPRUS, THE GAMBIA, TUVALU, ALBANIA, QATAR, KUWAIT, GUATEMALA, FINLAND, AFGHANISTAN, HONDURAS, HERZEGOVINA, MAURITANIA, TAIWAN (REPUBLIC OF CHINA), UGANDA, ST. VINCENT AND THE GRENADINES, FIJI, MAURITIUS, SWITZERLAND, PARAGUAY, URUGUAY, TAJIKISTAN, BURUNDI, MONTENEGRO, SOLOMON ISLANDS, GUINEA, ZIMBABWE, ESTONIA, COSTA RICA, CHAD, SUDAN, NAURU, TONGA, NORTH KOREA, UNITED KINGDOM, TRINIDAD AND TOBAGO, SLOVENIA, IRELAND, COLOMBIA, AZERBAIJAN, ARGENTINA, SURINAME, MARSHALL ISLANDS, BELARUS (BYELORUSSIA), EGYPT, PORTUGAL, ETHIOPIA, GERMANY, INDONESIA, CAPE VERDE, VATICAN CITY, BOSNIA, TURKMENISTAN, IRAQ, MICRONESIA, JAMAICA, ROMANIA, RUSSIA, EL SALVADOR, LAOS, GREECE, YEMEN, FRANCE, AUSTRIA, SIERRA LEONE, CENTRAL AFRICAN REPUBLIC, SERBIA, SYRIA, PANAMA, NIGER, SLOVAKIA]
Shuffled capitals: [Quito, Vienna, Lima, Kingston, Brazzaville, Andorra la Vella, Sana’a, Vilnius, Lome, Yaounde, Tunis, Algiers, Panama City, Nassau, Porto-Novo, Nairobi, San Jose, Moroni, Suva, Vientiane, Tehran, Riyadh, Santiago, San Salvador, Muscat, Tallinn, Damascus, Kingstown, Chisinau, Antananarivo, Ankara, Berlin, Sucre (legal)/La Paz(administrative), Belmopan, Belgrade, Washington, D.C., Roseau, Bratislava, Tegucigalpa, Lilongwe, Canberra, Sao Tome, Ljuijana, Havana, Luanda, Prague, Maseru, Palikir, Port of Spain, Harare, Bamako, Saint John’s, Abuja, Colombo, Amman, Ashkabad, P’yongyang, Addis Ababa, Santo Domingo, Lusaka, Singapore, Baghdad, Honaira, Cairo, Bairiki, Moscow, Khartoum, Freetown, -, Male, Malabo, Yamoussoukro, Nouakchott, Monrovia, Kampala, Tirana, Dalap-Uliga-Darrit, Caracas, Oslo, Reykjavik, Castries, Kyiv, Baku, Bujumbura, Taipei, Managua, Wellington, Riga, Sofia, Bucharest, Tbilisi, Fongafale, Banjul, Bangkok, Dakar, Abu Dhabi, Conakry, Brasilia, Islamabad, Kuala Lumpur, Warsaw, Mbabane, Rome, Budapest, Bridgetown, Amsterdam, Asuncion, Dijibouti, Bogota, Madrid, Beirut, < Port-Vila, Mexico City, Bandar Seri Begawan, Georgetown, Kabul, Accra, Athens, Valletta, Phnom Penh, Ulan Bator, Jakarta, Lisbon, Tripoli, Rabat, Dhaka, -, N’djamena, Tokyo, Pretoria/Cape Town, Mogadishu, San Marino, Windhoek, Port-au-Prince, Vaduz, Apia, Kuwait City, Gaberone, Victoria, Manama, Yerevan, Nuku’alofa, Yaren, Thimphu, Koror, Seoul, Asmara, Ouagadougou, Tashkent, London, Hanoi, Dodoma, Basseterre, Beijing, Port Louis, Port Moresby, Minsk, Nicosia, Kinshasa, ---, Buenos Aires, Ottawa, Manila, Zagreb, Sarajevo, Almaty, Katmandu, Montevideo, New Delhi, Dushanbe, Doha, Guatemala City, Kigali, Stockholm, Dublin, Podgorica, Bangui, Paramaribo, Helsinki, Copenhagen, Bissau, Libreville, Praia, Saint George’s, Rangoon, Paris, Monaco, Jerusalem, Brussels, Skopje, Maputo, Alma-Ata, Berne, Niamey, Luxembourg]
Shuffled countries: [SYRIA, IRAN, YEMEN, BARBADOS, NEVIS, BENIN, THE NETHERLANDS, AUSTRALIA, MICRONESIA, HERZEGOVINA, GUATEMALA, TANZANIA, SRI LANKA, ARMENIA, AUSTRIA, DOMINICAN REPUBLIC, THE GAMBIA, IRAQ, BHUTAN, SWITZERLAND, QATAR, INDONESIA, VENEZUELA, GRENADA, HAITI, JAPAN, BELARUS (BYELORUSSIA), CAMBODIA, SURINAME, KUWAIT, CZECH REPUBLIC, TRINIDAD AND TOBAGO, CANADA, NIGER, UNITED ARAB EMIRATES, ISRAEL, ERITREA, THAILAND, THE MALDIVES, MEXICO, JAMAICA, CONGO, LIBERIA, SINGAPORE, LESOTHO, PHILIPPINES, BRAZIL, MOLDOVA, GEORGIA, COLOMBIA, BURKINA FASO, POLAND, MAURITANIA, MALAWI, SOLOMON ISLANDS, TUNISIA, ZAMBIA, SWAZILAND, RWANDA, SUDAN, COTE D’IVOIR (IVORY COAST), HONDURAS, SLOVAKIA, INDIA, TONGA, LIBYA, SOUTH AFRICA, ZIMBABWE, LAOS, URUGUAY, MALTA, SEYCHELLES, TURKMENISTAN, ST. VINCENT AND THE GRENADINES, ST. LUCIA, SAUDI ARABIA, BISSAU, AZERBAIJAN, ALGERIA, TAJIKISTAN, NICARAGUA, MARSHALL ISLANDS, FRANCE, CAPE VERDE, BOSNIA, OMAN, TOGO, UNITED STATES OF AMERICA, MOROCCO, TURKEY, ST. KITTS, SOMALIA, LIECHTENSTEIN, NEW ZEALAND, VATICAN CITY, GUYANA, NEPAL, ANTIGUA AND BARBUDA, CROATIA, ICELAND, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), BULGARIA, MADAGASCAR, NAMIBIA, NIGERIA, GUINEA, VIETNAM, SOUTH KOREA, KIRIBATI, JORDAN, SPAIN, GHANA, VANUATU, UKRAINE, PORTUGAL, AFGHANISTAN, ROMANIA, MONTENEGRO, MACEDONIA, KENYA, BRUNEI, PANAMA, UGANDA, LATVIA, NORTH KOREA, SAN MARINO, BOLIVIA, GREECE, ANGOLA, TAIWAN (REPUBLIC OF CHINA), MAURITIUS, CHAD, NAURU, MYANMAR (BURMA), CENTRAL AFRICAN REPUBLIC, ARGENTINA, GERMANY, ANDORRA, NORWAY, PERU, SAO TOME E PRINCIPE, RUSSIA, MONGOLIA, BURUNDI, CYPRUS, COSTA RICA, LITHUANIA, BELIZE, CUBA, FIJI, GABON, MOZAMBIQUE, CHINA, SLOVENIA, ALBANIA, WESTERN SAMOA, FINLAND, DJIBOUTI, COMOROS, DOMINICA, EGYPT, BELGIUM, LEBANON, KAZAKSTAN, BAHAMAS, IRELAND, KYRGYZSTAN, ETHIOPIA, SIERRA LEONE, PARAGUAY, MONACO, SWEDEN, ESTONIA, SERBIA, PAPUA NEW GUINEA, MALI, ECUADOR, EQUATORIAL GUINEA, ITALY, BANGLADESH, CHILE, BAHRAIN, PAKISTAN, DENMARK, UNITED KINGDOM, CAMEROON, PALAU, SENEGAL, EL SALVADOR, BOTSWANA, HUNGARY, LUXEMBOURG, TUVALU, UZBEKISTAN, MALAYSIA]
Shuffled capitals: [Maputo, Manila, Algiers, Mbabane, Victoria, Sao Tome, Abuja, Bairiki, Palikir, Kingston, Managua, Stockholm, Tokyo, Yerevan, Praia, Panama City, Nairobi, Abu Dhabi, Suva, Dodoma, Moscow, Kampala, P’yongyang, Nicosia, Rome, Sucre (legal)/La Paz(administrative), Asuncion, Maseru, Damascus, Brazzaville, Port Moresby, Bridgetown, Ulan Bator, Quito, Colombo, Islamabad, Vaduz, Bucharest, Bogota, Dushanbe, Kuala Lumpur, Harare, Mexico City, Kuwait City, Nassau, Paris, Lome, -, Addis Ababa, Montevideo, Caracas, Yaounde, Libreville, Lisbon, San Jose, Monrovia, Tehran, Dublin, Skopje, Lusaka, Windhoek, Saint George’s, Baku, Banjul, Buenos Aires, Amsterdam, Koror, Tunis, Belgrade, Almaty, San Salvador, Riyadh, Luxembourg, Havana, Santiago, Kyiv, Santo Domingo, Conakry, Sofia, Port of Spain, Canberra, Dalap-Uliga-Darrit, Seoul, Gaberone, Bangkok, Andorra la Vella, Budapest, Tallinn, Yaren, Katmandu, Lilongwe, Madrid, Thimphu, < Port-Vila, Sana’a, Moroni, Dhaka, Mogadishu, Nuku’alofa, Georgetown, Bujumbura, Tbilisi, Tegucigalpa, Berlin, Wellington, Reykjavik, Vilnius, Nouakchott, Manama, Kabul, Monaco, Amman, Luanda, Sarajevo, Apia, Ouagadougou, Bratislava, Valletta, Cairo, Freetown, Brussels, Athens, Berne, Fongafale, Hanoi, N’djamena, Alma-Ata, Antananarivo, Paramaribo, Yamoussoukro, London, Tashkent, Ljuijana, Roseau, Accra, Dijibouti, Ashkabad, Port-au-Prince, Lima, Kigali, Malabo, Chisinau, Ankara, Khartoum, Baghdad, Singapore, Brasilia, Castries, Ottawa, Porto-Novo, Saint John’s, Male, Tripoli, Honaira, Rangoon, Phnom Penh, Beijing, Pretoria/Cape Town, New Delhi, San Marino, Muscat, Doha, Prague, Beirut, Guatemala City, Minsk, Dakar, Oslo, Jakarta, Taipei, Washington, D.C., ---, Zagreb, Kingstown, Bamako, Podgorica, Bangui, -, Riga, Niamey, Rabat, Helsinki, Port Louis, Vientiane, Belmopan, Copenhagen, Bandar Seri Begawan, Basseterre, Jerusalem, Bissau, Tirana, Vienna, Kinshasa, Asmara, Warsaw]

Process finished with exit code 0

 */
